'use strict';

// Every IPC handler module registers its channels with ipcMain when it loads.
require('./ai');
require('./categories');
require('./collections');
require('./backup');
require('./context-menu');
require('./context-menu-generate-tags');
require('./context-menu-pull-metadata');
require('./files');
require('./hashes');
require('./link-import');
require('./makerworld');
require('./metadata');
require('./model-save');
require('./models');
require('./notifications');
require('./organize');
require('./parts');
require('./previews');
require('./previews-other-formats');
require('./print-events');
require('./printers');
require('./scan');
require('./server-access');
require('./settings');
require('./slicers');
require('./system-report');
require('./tags');
require('./thumbnails');
require('./updates');
require('./uploads');
